name: Swift

on:
  schedule:
    - cron:  '20 2 * * *'
  push:
    branches:
      - master
      - develop
      - feature/*

  pull_request:
    branches:
      - master
      - develop
      - feature/*

jobs:
  test:
    name: Complete Test Suite
    runs-on: self-hosted
    strategy:
      matrix:
        destination: ['platform=macOS,arch=arm64']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build and test PolynomialRegression Test Suite
      run: .github/workflows/RunCompleteUnitTestSuite.sh
      env:
        destination: ${{ matrix.destination }}
        LC_CTYPE: en_US.UTF-8
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/build/reports/junit.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_failure: true


