name: Continuous Run

on:
  schedule:
    - cron:  '20 2 * * *'
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  test:
    name: Complete Test Suite
    runs-on: self-hosted
    steps:
    - name: Set Required PATH Variable
      run: |
        echo "/usr/local/bin:$PATH" >> $GITHUB_PATH
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build And Test PolynomialRegression Test Suite
      run: .github/workflows/RunCompleteUnitTestSuite.sh
      env:
        destination: "platform=macOS,arch=arm64"
        LC_CTYPE: en_US.UTF-8
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/build/reports/junit.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_failure: true


